name: CICD
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        # set up DockerHub credentials
        # these are saved to org secrets so every new repo should be able to access it
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # set up Docker image name and tag; these should be defined in your GitHub repository's variables in repo settings
          # ex: carclinchda/email-processing-service:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ vars.VERSION_TAG }}